name: Release

on:
  push:
    tags:
      - "v*"

env:
  FRONTEND_ROOT: frontend
  BACKEND_ROOT: entari_plugin_webui
  PACKAGE_NAME: entari_plugin_webui

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: ${{ env.FRONTEND_ROOT }}/package-lock.json

      - name: Build frontend
        working-directory: ${{ env.FRONTEND_ROOT }}
        run: |
          npm install -no-fund
          npm run build -no-fund

      - name: Copy frontend -> backend
        run: |
          set -e
          rm -rf "$BACKEND_ROOT/$PACKAGE_NAME/frontend"
          mkdir -p "$BACKEND_ROOT/$PACKAGE_NAME/frontend"
          cp -r "$FRONTEND_ROOT/dist"/* "$BACKEND_ROOT/$PACKAGE_NAME/frontend/"

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: "3.11"
          cache: true
          cache-dependency-path: ${{ env.BACKEND_ROOT }}/pdm.lock

      - name: Build wheel
        working-directory: ${{ env.BACKEND_ROOT }}
        run: pdm build

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: ${{ github.event.head_commit.message }}
          files: |
            ${{ env.BACKEND_ROOT }}/dist/*.whl
            ${{ env.BACKEND_ROOT }}/dist/*.tar.gz
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}